---
title: "dogwalkr"
author: "IH"
date: "07/02/2021"
output: html_document
---

Boundary data from:

Source: Office for National Statistics licensed under the Open Government Licence v.3.0

Contains OS data © Crown copyright and database right [2017]

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(here)
```

```{r}
meters_in_mile <- 1609

ca <- read_sf(here(
  "Local_Authority_Districts__December_2017__Boundaries_GB_BUC-shp",
  "Local_Authority_Districts__December_2017__Boundaries_GB_BUC.shp"
))

# st_crs(ca)
```




```{r, fig.width=10}
ca_buffer <- ca %>%
  st_buffer(dist = 5 * meters_in_mile) %>% 
  mutate(stroke = 0.2)

ca %>% 
  mutate(stroke = 0) %>% 
  bind_rows(ca_buffer) %>% 
  filter(LAD17NM %in% c("Scottish Borders", "City of Edinburgh")) %>%
  st_transform(ca1, crs = "+proj=latlon +datum=WGS84") %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(fillColor = "blue", stroke = ~stroke,
              weight = 2, fillOpacity = 0.1) %>%
  addMeasure() %>%
  addScaleBar()
```
